#ifndef UUID_6C5AE035_9F3B_459F_85CE_D7D4962C8CB6
#define UUID_6C5AE035_9F3B_459F_85CE_D7D4962C8CB6

#include <QtCore/QScopedPointer>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE
namespace Ui
{
    class Widget;
}
QT_END_NAMESPACE

class Widget : public QWidget
{
    Q_OBJECT
public:
    explicit Widget(QWidget* parent = nullptr);
    ~Widget() override;
private slots:
    void doDisplay();
    void on_lineEdit_textChanged(const QString& text);
private:
    // Smat pointer to an instance of the Ui class
    // generated by the uic from xml description
    // produced by designer.
    QScopedPointer<Ui::Widget> ui_;
};

#endif
